// ---------------------------------------------------------------------------
// Curriculum model — verbs, tenses, levels, and generated lesson items.
// This replaces the old hand-written per-exercise data arrays: conjugations are
// generated by the engine so adding a verb/tense is a data-only change.
// ---------------------------------------------------------------------------

export type Tense = "presente" | "passato_prossimo" | "imperfetto" | "futuro_semplice";

export const TENSES: Tense[] = ["presente", "passato_prossimo", "imperfetto", "futuro_semplice"];

/** Level at which each tense is introduced (lower = earlier). */
export const TENSE_LEVEL: Record<Tense, number> = {
  presente: 1,
  passato_prossimo: 2,
  imperfetto: 3,
  futuro_semplice: 4,
};

export const TENSE_LABEL: Record<Tense, { it: string; en: string; es: string }> = {
  presente: { it: "Presente", en: "Present", es: "Presente" },
  passato_prossimo: { it: "Passato prossimo", en: "Present perfect", es: "Pretérito perfecto" },
  imperfetto: { it: "Imperfetto", en: "Imperfect", es: "Imperfecto" },
  futuro_semplice: { it: "Futuro semplice", en: "Simple future", es: "Futuro simple" },
};

export type VerbGroup = "are" | "ere" | "ire" | "ire-isc";

export type VerbEntry = {
  id: string;
  infinitive: string;
  /** Translation of the infinitive, used in prompts. */
  en: string;
  es: string;
  group: VerbGroup;
  auxiliary: "avere" | "essere";
  /** 1 = most common/easy, 5 = advanced. Drives level ordering. */
  level: number;
  /** Full 6-form overrides where a tense is irregular. */
  irregular?: Partial<Record<Tense, string[]>>;
  /** Irregular past participle (for passato prossimo). */
  participle?: string;
  /** Irregular futuro stem (before ò/ai/à/emo/ete/anno). */
  futuroStem?: string;
  /** Irregular imperfetto stem (before vo/vi/va/vamo/vate/vano). */
  imperfettoStem?: string;
};

// --- Generated lesson items ------------------------------------------------

export type FlashItem = {
  kind: "flash";
  verbId: string;
  tense: Tense;
  pronounIndex: number;
  answer: string;
};

export type ChoiceItem = {
  kind: "choice";
  verbId: string;
  tense: Tense;
  pronounIndex: number;
  answer: string;
  options: string[];
};

export type MatchItem = {
  kind: "match";
  verbId: string;
  tense: Tense;
  pairs: { pronoun: string; form: string }[];
};

export type CompleteItem = {
  kind: "complete";
  verbId: string;
  tense: Tense;
  pronounIndex: number;
  answer: string;
};

export type IntroItem = {
  kind: "intro";
  verbIds: string[];
  tense: Tense;
};

export type LessonItem = FlashItem | ChoiceItem | MatchItem | CompleteItem | IntroItem;

export type Lesson = {
  verbIds: string[];
  tense: Tense;
  items: LessonItem[];
};

// --- Curriculum path -------------------------------------------------------

export type Unit = {
  id: string;
  level: number;
  tense: Tense;
  verbIds: string[];
  titleIt: string;
  titleEn: string;
  titleEs: string;
};
