// ---------------------------------------------------------------------------
// Verb registry — leveled from common/easy (1) to advanced (5).
// Only irregular forms are stored; regular forms are generated by the engine.
// ---------------------------------------------------------------------------

import type { VerbEntry } from "./types";

export const VERBS: VerbEntry[] = [
  // ---- Level 1: the essentials --------------------------------------------
  {
    id: "essere", infinitive: "essere", en: "to be", es: "ser/estar",
    group: "ere", auxiliary: "essere", level: 1,
    irregular: {
      presente: ["sono", "sei", "è", "siamo", "siete", "sono"],
      imperfetto: ["ero", "eri", "era", "eravamo", "eravate", "erano"],
    },
    participle: "stato", futuroStem: "sar",
  },
  {
    id: "avere", infinitive: "avere", en: "to have", es: "tener/haber",
    group: "ere", auxiliary: "avere", level: 1,
    irregular: { presente: ["ho", "hai", "ha", "abbiamo", "avete", "hanno"] },
    futuroStem: "avr",
  },
  {
    id: "fare", infinitive: "fare", en: "to do/make", es: "hacer",
    group: "are", auxiliary: "avere", level: 1,
    irregular: { presente: ["faccio", "fai", "fa", "facciamo", "fate", "fanno"] },
    participle: "fatto", futuroStem: "far", imperfettoStem: "face",
  },
  {
    id: "stare", infinitive: "stare", en: "to stay/be", es: "estar",
    group: "are", auxiliary: "essere", level: 1,
    irregular: { presente: ["sto", "stai", "sta", "stiamo", "state", "stanno"] },
    participle: "stato", futuroStem: "star",
  },
  {
    id: "andare", infinitive: "andare", en: "to go", es: "ir",
    group: "are", auxiliary: "essere", level: 1,
    irregular: { presente: ["vado", "vai", "va", "andiamo", "andate", "vanno"] },
    futuroStem: "andr",
  },

  // ---- Level 2: modals + high-frequency irregulars ------------------------
  {
    id: "dire", infinitive: "dire", en: "to say", es: "decir",
    group: "ire", auxiliary: "avere", level: 2,
    irregular: { presente: ["dico", "dici", "dice", "diciamo", "dite", "dicono"] },
    participle: "detto", imperfettoStem: "dice",
  },
  {
    id: "dare", infinitive: "dare", en: "to give", es: "dar",
    group: "are", auxiliary: "avere", level: 2,
    irregular: { presente: ["do", "dai", "dà", "diamo", "date", "danno"] },
    futuroStem: "dar",
  },
  {
    id: "potere", infinitive: "potere", en: "can/to be able", es: "poder",
    group: "ere", auxiliary: "avere", level: 2,
    irregular: { presente: ["posso", "puoi", "può", "possiamo", "potete", "possono"] },
    futuroStem: "potr",
  },
  {
    id: "volere", infinitive: "volere", en: "to want", es: "querer",
    group: "ere", auxiliary: "avere", level: 2,
    irregular: { presente: ["voglio", "vuoi", "vuole", "vogliamo", "volete", "vogliono"] },
    futuroStem: "vorr",
  },
  {
    id: "dovere", infinitive: "dovere", en: "must/to have to", es: "deber",
    group: "ere", auxiliary: "avere", level: 2,
    irregular: { presente: ["devo", "devi", "deve", "dobbiamo", "dovete", "devono"] },
    futuroStem: "dovr",
  },

  // ---- Level 3: common regular -are ---------------------------------------
  { id: "parlare", infinitive: "parlare", en: "to speak", es: "hablar", group: "are", auxiliary: "avere", level: 3 },
  { id: "abitare", infinitive: "abitare", en: "to live/reside", es: "vivir/residir", group: "are", auxiliary: "avere", level: 3 },
  { id: "lavorare", infinitive: "lavorare", en: "to work", es: "trabajar", group: "are", auxiliary: "avere", level: 3 },
  { id: "mangiare", infinitive: "mangiare", en: "to eat", es: "comer", group: "are", auxiliary: "avere", level: 3 },
  { id: "studiare", infinitive: "studiare", en: "to study", es: "estudiar", group: "are", auxiliary: "avere", level: 3 },

  // ---- Level 4: common -ere (some irregular participles) ------------------
  { id: "credere", infinitive: "credere", en: "to believe", es: "creer", group: "ere", auxiliary: "avere", level: 4 },
  { id: "prendere", infinitive: "prendere", en: "to take", es: "tomar", group: "ere", auxiliary: "avere", level: 4, participle: "preso" },
  { id: "leggere", infinitive: "leggere", en: "to read", es: "leer", group: "ere", auxiliary: "avere", level: 4, participle: "letto" },
  { id: "scrivere", infinitive: "scrivere", en: "to write", es: "escribir", group: "ere", auxiliary: "avere", level: 4, participle: "scritto" },
  { id: "vivere", infinitive: "vivere", en: "to live", es: "vivir", group: "ere", auxiliary: "avere", level: 4, participle: "vissuto", futuroStem: "vivr" },

  // ---- Level 5: -ire, incl. -isc- and irregulars --------------------------
  { id: "dormire", infinitive: "dormire", en: "to sleep", es: "dormir", group: "ire", auxiliary: "avere", level: 5 },
  { id: "partire", infinitive: "partire", en: "to leave/depart", es: "partir/salir", group: "ire", auxiliary: "essere", level: 5 },
  { id: "capire", infinitive: "capire", en: "to understand", es: "entender", group: "ire-isc", auxiliary: "avere", level: 5 },
  { id: "finire", infinitive: "finire", en: "to finish", es: "terminar", group: "ire-isc", auxiliary: "avere", level: 5 },
  { id: "preferire", infinitive: "preferire", en: "to prefer", es: "preferir", group: "ire-isc", auxiliary: "avere", level: 5 },
  {
    id: "venire", infinitive: "venire", en: "to come", es: "venir",
    group: "ire", auxiliary: "essere", level: 5,
    irregular: { presente: ["vengo", "vieni", "viene", "veniamo", "venite", "vengono"] },
    participle: "venuto", futuroStem: "verr",
  },
  {
    id: "uscire", infinitive: "uscire", en: "to go out", es: "salir",
    group: "ire", auxiliary: "essere", level: 5,
    irregular: { presente: ["esco", "esci", "esce", "usciamo", "uscite", "escono"] },
  },
];

const BY_ID = new Map(VERBS.map((v) => [v.id, v]));

export function getVerb(id: string): VerbEntry | undefined {
  return BY_ID.get(id);
}

export function getVerbs(ids: string[]): VerbEntry[] {
  return ids.map((id) => BY_ID.get(id)).filter((v): v is VerbEntry => !!v);
}

export const MAX_LEVEL = Math.max(...VERBS.map((v) => v.level));

/** Verbs available at or below a given level, in registry order. */
export function verbsUpToLevel(level: number): VerbEntry[] {
  return VERBS.filter((v) => v.level <= level);
}
